name: Include build with all optional modules

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    
    # Install Qt and set the appropriate architecture based on the OS
    - uses: jurplel/install-qt-action@v3
      with:
        # Conditional selection of architecture based on OS
        arch: ${{ matrix.os == 'ubuntu-latest' && 'gcc_64' || 'win64_msvc2019_64' }}
        # Same Qt modules for both OS
        archives: 'icu qtbase qtmultimedia qtgamepad qtsystems qtlocation qtsensors'

    # Build step
    - name: Build
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          qmake && make
        else
          qmake && nmake
