name: Check style

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  style:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install clang-format-19
      run: sudo apt-get install -y clang-format-19
    - name: Check style
      run: tools/check-style.sh
